server:
    port: 8001
spring:
    datasource:
        password: Valleon6
        url: jdbc:postgresql://localhost:5432/rytdatabase
        username: postgres
    jpa:
#        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        hibernate:
            ddl-auto: update
#            naming:
#                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
                format_sql: true
        show-sql: true