server:
    port: 8001
spring:
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    datasource:
        password: Valleon6
        url: jdbc:postgresql://localhost:5432/rytdatabase
        username: postgres
    jpa:
#        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        hibernate:
            ddl-auto: update
#            naming:
#                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
                format_sql: true
        show-sql: false
    main:
        allow-circular-references: true
    servlet:
        multipart:
            enabled: true
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-authentication-method: post
                        client-id: 497659411913-gvk3f86dpuhhb5o1jra0hscp795lcane.apps.googleusercontent.com
                        client-secret: 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
                        redirect-uri: https://localhost:9001/login/oauth2/code/google
                        scope:
                            - email
                            - profile
jwt:
    adminKey:
        passwordpasswordpasswordpasswordpasswordpasswordpasswordpassword
cloudinary_name:
    wingsmarket
cloudinary_api_key:
    834576764474828
cloudinary_api_secret:
    UissCDu2wcYRHKAdfJ2yuppCVyM

